apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "clinica-app"
  namespace: "default"
  labels:
    app: "clinica-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "clinica-app"
  template:
    metadata:
      labels:
        app: "clinica-app"
    spec:
      containers:
      - name: "clinica-app"
        image: "gcr.io/clinica-410702/github.com/bi-dall/clinicaapp"
